#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: demoshop_index
        permanent: false